-- Hand-authored initial migration.
--
-- This was written directly against schema.prisma rather than generated by
-- `prisma migrate dev`, because generating it requires downloading Prisma's
-- engine binaries from binaries.prisma.sh, which was not reachable from the
-- environment this project was built in. It follows Prisma's standard
-- migration conventions exactly (table/column naming via @map, enum types,
-- foreign keys, indexes) so `prisma migrate deploy` applies and tracks it
-- normally — this is a one-time gap, not an ongoing pattern; every
-- migration after this one should be generated normally with
-- `prisma migrate dev` once you have a working local Postgres.

-- Enums
CREATE TYPE "ConnectorType" AS ENUM ('NETSUITE', 'SHOPIFY', 'SALESFORCE', 'GENERIC_REST');
CREATE TYPE "JobStatus" AS ENUM ('QUEUED', 'RUNNING', 'SUCCESS', 'FAILED', 'RETRYING');

-- plans
CREATE TABLE "plans" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "monthlySyncQuota" INTEGER NOT NULL,
    "maxConcurrentJobs" INTEGER NOT NULL DEFAULT 2,
    "rateLimitPerMin" INTEGER NOT NULL DEFAULT 30,

    CONSTRAINT "plans_pkey" PRIMARY KEY ("id")
);

-- tenants
CREATE TABLE "tenants" (
    "id" TEXT NOT NULL DEFAULT gen_random_uuid()::text,
    "name" TEXT NOT NULL,
    "planId" TEXT NOT NULL DEFAULT 'free',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "tenants_pkey" PRIMARY KEY ("id")
);

-- api_keys
CREATE TABLE "api_keys" (
    "id" TEXT NOT NULL DEFAULT gen_random_uuid()::text,
    "tenantId" TEXT NOT NULL,
    "keyHash" TEXT NOT NULL,
    "label" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "revokedAt" TIMESTAMP(3),

    CONSTRAINT "api_keys_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "api_keys_keyHash_key" ON "api_keys"("keyHash");

-- connections
CREATE TABLE "connections" (
    "id" TEXT NOT NULL DEFAULT gen_random_uuid()::text,
    "tenantId" TEXT NOT NULL,
    "connectorType" "ConnectorType" NOT NULL,
    "label" TEXT NOT NULL,
    "credentialsEnc" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'pending',
    "lastCheckedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "connections_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "connections_tenantId_idx" ON "connections"("tenantId");

-- mappings
CREATE TABLE "mappings" (
    "id" TEXT NOT NULL DEFAULT gen_random_uuid()::text,
    "tenantId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "sourceConnectionId" TEXT NOT NULL,
    "targetConnectionId" TEXT NOT NULL,
    "sourceObject" TEXT NOT NULL,
    "targetObject" TEXT NOT NULL,
    "fieldMappings" JSONB NOT NULL,
    "triggerType" TEXT NOT NULL DEFAULT 'poll',
    "pollIntervalSec" INTEGER DEFAULT 300,
    "webhookSecret" TEXT,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "mappings_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "mappings_tenantId_idx" ON "mappings"("tenantId");

-- jobs
CREATE TABLE "jobs" (
    "id" TEXT NOT NULL DEFAULT gen_random_uuid()::text,
    "tenantId" TEXT NOT NULL,
    "mappingId" TEXT NOT NULL,
    "status" "JobStatus" NOT NULL DEFAULT 'QUEUED',
    "recordsRead" INTEGER NOT NULL DEFAULT 0,
    "recordsWritten" INTEGER NOT NULL DEFAULT 0,
    "errorMessage" TEXT,
    "attempt" INTEGER NOT NULL DEFAULT 1,
    "startedAt" TIMESTAMP(3),
    "finishedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "jobs_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "jobs_tenantId_createdAt_idx" ON "jobs"("tenantId", "createdAt");

-- usage_counters
CREATE TABLE "usage_counters" (
    "id" TEXT NOT NULL DEFAULT gen_random_uuid()::text,
    "tenantId" TEXT NOT NULL,
    "date" TIMESTAMP(3) NOT NULL,
    "syncCount" INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT "usage_counters_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "usage_counters_tenantId_date_key" ON "usage_counters"("tenantId", "date");

-- backup_configs
CREATE TABLE "backup_configs" (
    "id" TEXT NOT NULL DEFAULT 'default',
    "enabled" BOOLEAN NOT NULL DEFAULT false,
    "cronSchedule" TEXT NOT NULL DEFAULT '0 3 * * *',
    "retentionDays" INTEGER NOT NULL DEFAULT 30,
    "storageProvider" TEXT NOT NULL DEFAULT 's3',
    "s3Bucket" TEXT,
    "s3Region" TEXT,
    "s3CredentialsEnc" TEXT,
    "localPath" TEXT DEFAULT '/var/backups/integration-hub',
    "lastRunAt" TIMESTAMP(3),
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "backup_configs_pkey" PRIMARY KEY ("id")
);

-- backup_runs
CREATE TABLE "backup_runs" (
    "id" TEXT NOT NULL DEFAULT gen_random_uuid()::text,
    "configId" TEXT NOT NULL DEFAULT 'default',
    "trigger" TEXT NOT NULL DEFAULT 'scheduled',
    "status" TEXT NOT NULL DEFAULT 'running',
    "startedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "finishedAt" TIMESTAMP(3),
    "sizeBytes" INTEGER,
    "location" TEXT,
    "errorMessage" TEXT,

    CONSTRAINT "backup_runs_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "backup_runs_configId_startedAt_idx" ON "backup_runs"("configId", "startedAt");

-- Foreign keys
ALTER TABLE "tenants" ADD CONSTRAINT "tenants_planId_fkey" FOREIGN KEY ("planId") REFERENCES "plans"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "api_keys" ADD CONSTRAINT "api_keys_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "connections" ADD CONSTRAINT "connections_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "mappings" ADD CONSTRAINT "mappings_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "mappings" ADD CONSTRAINT "mappings_sourceConnectionId_fkey" FOREIGN KEY ("sourceConnectionId") REFERENCES "connections"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "mappings" ADD CONSTRAINT "mappings_targetConnectionId_fkey" FOREIGN KEY ("targetConnectionId") REFERENCES "connections"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "jobs" ADD CONSTRAINT "jobs_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "jobs" ADD CONSTRAINT "jobs_mappingId_fkey" FOREIGN KEY ("mappingId") REFERENCES "mappings"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "usage_counters" ADD CONSTRAINT "usage_counters_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "backup_runs" ADD CONSTRAINT "backup_runs_configId_fkey" FOREIGN KEY ("configId") REFERENCES "backup_configs"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
